package checksum

import (
	"crypto/sha256"
	"encoding/hex"
	"strings"
	"testing"
)

func TestFindFile(t *testing.T) {
	const artifact = "myapp_1.2.3_linux_amd64.tar.gz"

	tests := []struct {
		name     string
		artifact string
		names    []string
		want     string
	}{
		{
			name:     "per-artifact file",
			artifact: artifact,
			names:    []string{artifact, artifact + ".sha256"},
			want:     artifact + ".sha256",
		},
		{
			name:     "per-artifact file with the sha256sum extension",
			artifact: artifact,
			names:    []string{artifact, artifact + ".sha256sum"},
			want:     artifact + ".sha256sum",
		},
		{
			name:     "per-artifact file wins over an aggregate one",
			artifact: artifact,
			names:    []string{artifact, "checksums.txt", artifact + ".sha256"},
			want:     artifact + ".sha256",
		},
		{
			name:     "aggregate checksums.txt",
			artifact: artifact,
			names:    []string{artifact, "checksums.txt"},
			want:     "checksums.txt",
		},
		{
			name:     "aggregate SHA256SUMS regardless of case",
			artifact: artifact,
			names:    []string{artifact, "SHA256SUMS"},
			want:     "SHA256SUMS",
		},
		{
			name:     "aggregate name carrying a project prefix",
			artifact: artifact,
			names:    []string{artifact, "myapp_1.2.3_checksums.txt"},
			want:     "myapp_1.2.3_checksums.txt",
		},
		{
			name:     "the checksum file of another artifact is not used",
			artifact: artifact,
			names:    []string{artifact, "myapp_1.2.3_darwin_arm64.tar.gz.sha256"},
			want:     "",
		},
		{
			name:     "no checksum file",
			artifact: artifact,
			names:    []string{artifact, "README.md"},
			want:     "",
		},
		{
			name:     "no files at all",
			artifact: artifact,
			names:    nil,
			want:     "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := FindFile(tt.artifact, tt.names); got != tt.want {
				t.Errorf("FindFile(%q, %v) = %q, want %q", tt.artifact, tt.names, got, tt.want)
			}
		})
	}
}

func TestParse(t *testing.T) {
	const (
		digestA = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
		digestB = "0000000000000000000000000000000000000000000000000000000000000000"
	)

	tests := []struct {
		name     string
		content  string
		artifact string
		want     string
		wantErr  bool
	}{
		{
			name:     "sha256sum output",
			content:  digestA + "  app_linux_amd64.tar.gz\n" + digestB + "  app_darwin_arm64.tar.gz\n",
			artifact: "app_linux_amd64.tar.gz",
			want:     digestA,
		},
		{
			name:     "binary mode marker",
			content:  digestA + " *app_linux_amd64.tar.gz\n",
			artifact: "app_linux_amd64.tar.gz",
			want:     digestA,
		},
		{
			name:     "a recorded path is matched on its base name",
			content:  digestA + "  dist/app_linux_amd64.tar.gz\n",
			artifact: "app_linux_amd64.tar.gz",
			want:     digestA,
		},
		{
			name:     "a lone digest covers the artifact",
			content:  digestA + "\n",
			artifact: "app_linux_amd64.tar.gz",
			want:     digestA,
		},
		{
			name:     "uppercase digest is normalized",
			content:  strings.ToUpper(digestA) + "  app_linux_amd64.tar.gz\n",
			artifact: "app_linux_amd64.tar.gz",
			want:     digestA,
		},
		{
			name:     "comments and blank lines are ignored",
			content:  "# generated by ci\n\n" + digestA + "  app_linux_amd64.tar.gz\n",
			artifact: "app_linux_amd64.tar.gz",
			want:     digestA,
		},
		{
			name:     "artifact absent from an aggregate file",
			content:  digestA + "  app_darwin_arm64.tar.gz\n",
			artifact: "app_linux_amd64.tar.gz",
			wantErr:  true,
		},
		{
			name:     "a lone digest among several lines is not assumed",
			content:  digestA + "\n" + digestB + "  app_darwin_arm64.tar.gz\n",
			artifact: "app_linux_amd64.tar.gz",
			wantErr:  true,
		},
		{
			name:     "not a checksum file",
			content:  "hello world\n",
			artifact: "app_linux_amd64.tar.gz",
			wantErr:  true,
		},
		{
			name:     "empty file",
			content:  "",
			artifact: "app_linux_amd64.tar.gz",
			wantErr:  true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := Parse([]byte(tt.content), tt.artifact)
			if tt.wantErr {
				if err == nil {
					t.Fatalf("Parse() = %q, want an error", got)
				}
				return
			}
			if err != nil {
				t.Fatalf("Parse() error: %v", err)
			}
			if got != tt.want {
				t.Errorf("Parse() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestVerify(t *testing.T) {
	data := []byte("artifact contents")
	sum := sha256.Sum256(data)
	digest := hex.EncodeToString(sum[:])

	if err := Verify(data, digest); err != nil {
		t.Errorf("Verify() with the matching digest = %v, want nil", err)
	}

	err := Verify([]byte("tampered contents"), digest)
	if err == nil {
		t.Fatal("Verify() with a mismatched digest = nil, want an error")
	}
	if !strings.Contains(err.Error(), digest) {
		t.Errorf("error %q does not report the expected digest", err)
	}
}
