name: Lint by GolangCI LInt
on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main
jobs:
  golangci:
    name: GolongCI Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2.8
