name: Pages Staging

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - 'docs/**'

concurrency:
  group: "pages-staging-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0
      - name: Restore next cache
        uses: actions/cache@v4
        with:
          path: docs/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-
      - name: Install dependencies
        working-directory: docs
        run: bun install
      - name: Build and Export
        working-directory: docs
        run: bun run build
      - name: Verify build output
        run: ls -la docs/out/ || echo "Build output directory not found"
      - name: Deploy to GitHub Pages (Staging)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/out
          destination_dir: staging/${{ github.ref_name }}
          keep_files: true